local options = {
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "fish",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "haskell",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "odin",
        "printf",
        "python",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
        "angular",
        "bash",
        "css",
        "git_config",
        "git_rebase",
        "gitattributes",
        "html",
        "json",
        "java",
        "kotlin",
        "sql",
        "yaml",
        "javascript",
        "tsx",
        "typescript",
    },

    highlight = {
        enable = true,
        use_languagetree = true,
    },

    indent = { enable = true },
    autotag = {
        enable = true,
    },
    query_linter = {
        enable = true,
        use_virtual_test = true,
        lint_events = { "BufWrite", "CursorHold" },
    },
}

require("nvim-treesitter.configs").setup(options)
